"use client";

import React from 'react';
import ReactMarkdown from 'react-markdown';
import Link from 'next/link';
import { FaBullseye, FaGooglePlay } from 'react-icons/fa6';
import remarkGfm from 'remark-gfm';

const privacyPolicyContent = `
# Privacy Policy for GoalFocus

Last updated: Jan 21, 2026

This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

## Interpretation and Definitions

### Interpretation
The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

### Definitions
For the purposes of this Privacy Policy:
*   **Account** means a unique account created for You to access our Service or parts of our Service.
*   **Application** refers to GoalFocus, the software program provided by the Company.
*   **Company** (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to GoalFocus.
*   **Device** means any device that can access the Service such as a computer, a cell phone or a digital tablet.
*   **Personal Data** is any information that relates to an identified or identifiable individual.
*   **Service** refers to the Application.
*   **Usage Data** refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
*   **You** means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

## Collecting and Using Your Personal Data

### Types of Data Collected

#### Personal Data
While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
*   Usage Data

#### Usage Data
Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.

### Use of Your Personal Data
The Company may use Personal Data for the following purposes:
*   **To provide and maintain our Service**, including to monitor the usage of our Service.
*   **To manage Your Account:** to manage Your registration as a user of the Service. 
*   **To contact You:** To contact You regarding updates or informative communications related to the functionalities, products or contracted services, including security updates.
*   **For business transfers:** We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.
*   **For other purposes**: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.

### Retention of Your Personal Data
The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.

The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service.

### Transfer of Your Personal Data
Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.

### Delete Your Personal Data
You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.

You may update, amend, or delete Your information at any time by visiting the account settings section that allows you to manage Your personal information.

### Disclosure of Your Personal Data
Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).

The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
*   Comply with a legal obligation
*   Protect and defend the rights or property of the Company
*   Prevent or investigate possible wrongdoing in connection with the Service
*   Protect the personal safety of Users of the Service or the public
*   Protect against legal liability

### Security of Your Personal Data
The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.

## Children's Privacy
Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.

## Changes to this Privacy Policy
We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

## Contact Us
If you have any questions about this Privacy Policy, You can contact us:
*   By visiting this page on our website: [https://www.pushkaragnihotri.me/](https://www.pushkaragnihotri.me/)
`;

export default function GoalFocusPrivacyPolicy() {
    return (
        <div className="bg-[#fcfdfc] dark:bg-[#090b0a] min-h-screen text-slate-900 dark:text-slate-100 font-sans selection:bg-[#13ec49]/30 selection:text-slate-900 dark:selection:text-white relative">
            {/* Subtle Grid Background */}
            <div className="fixed inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] pointer-events-none z-0"></div>

            {/* Navigation (GoalFocus Brand, Not Portfolio) */}
            <nav className="fixed top-0 left-0 right-0 z-50 flex justify-between items-center px-6 md:px-10 py-4 backdrop-blur-xl border-b border-slate-200/50 dark:border-white/5 bg-white/70 dark:bg-[#090b0a]/70">
                <Link href="/goal-focus" className="text-xl font-bold tracking-tight flex items-center gap-2.5 group">
                    <div className="w-8 h-8 rounded-lg bg-[#101813] dark:bg-white flex items-center justify-center shadow-md">
                        <FaBullseye className="text-[#13ec49] text-sm" />
                    </div>
                    <span className="text-slate-900 dark:text-white font-semibold">Goal<span className="text-slate-500 font-normal">Focus</span></span>
                </Link>
                <div className="flex items-center gap-6">
                    <a href="https://play.google.com/store/apps/details?id=me.pushkaragnihotri.goalfocus&pcampaignid=web_share" target="_blank" rel="noopener noreferrer" className="flex px-5 py-2 rounded-full bg-slate-900 hover:bg-slate-800 dark:bg-white dark:hover:bg-slate-200 text-white dark:text-[#090b0a] text-sm font-semibold transition-all items-center gap-2 shadow-sm">
                        <FaGooglePlay className="text-xs" /> Download
                    </a>
                </div>
            </nav>

            {/* Main Content Area */}
            <main className="relative z-10 pt-32 pb-24 px-6 md:px-12 max-w-4xl mx-auto">
                <div className="bg-white dark:bg-[#111613] rounded-3xl p-8 md:p-14 border border-slate-200/80 dark:border-white/5 shadow-xl dark:shadow-[0_20px_60px_rgba(0,0,0,0.6)]">
                    <article className="prose prose-slate dark:prose-invert max-w-none 
                        prose-headings:font-bold prose-headings:tracking-tight 
                        prose-h1:text-3xl md:prose-h1:text-4xl prose-h1:mb-8
                        prose-h2:text-2xl prose-h2:mt-10 prose-h2:mb-4 prose-h2:border-b prose-h2:border-slate-100 dark:prose-h2:border-white/5 prose-h2:pb-2
                        prose-h3:text-lg prose-h3:text-slate-700 dark:prose-h3:text-slate-300
                        prose-p:text-slate-600 dark:prose-p:text-slate-400 prose-p:leading-relaxed
                        prose-a:text-[#13ec49] prose-a:no-underline hover:prose-a:underline
                        prose-ul:text-slate-600 dark:prose-ul:text-slate-400
                        prose-strong:text-slate-800 dark:prose-strong:text-slate-200"
                    >
                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                            {privacyPolicyContent}
                        </ReactMarkdown>
                    </article>
                </div>
            </main>

            {/* Simple Footer */}
            <footer className="relative z-10 px-6 py-12 border-t border-slate-200/80 dark:border-white/5 bg-transparent mt-12">
                <div className="max-w-4xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
                    <div className="flex items-center gap-2.5">
                        <div className="w-6 h-6 rounded-md bg-[#101813] dark:bg-white flex items-center justify-center opacity-70">
                            <FaBullseye className="text-[#13ec49] text-[10px]" />
                        </div>
                        <span className="text-sm font-bold tracking-tight text-slate-500">Goal<span className="font-normal">Focus</span> Legal</span>
                    </div>
                    <p className="text-slate-400 dark:text-slate-600 text-xs font-medium">© {new Date().getFullYear()} Pushkar Agnihotri.</p>
                </div>
            </footer>
        </div>
    );
}
